//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class NRMT_ESK
    {
        public decimal ID { get; set; }
        public string TECH_NOTES { get; set; }
        public string LBL { get; set; }
        public string JUR_NAME_F { get; set; }
        public string TECH_NAME { get; set; }
        public string JUR_NAME_F_LAT { get; set; }
        public string JUR_NAME_LAT { get; set; }
        public string JUR_NAME { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string OKPO { get; set; }
        public string OKDP { get; set; }
        public string OGRN { get; set; }
        public string OKVED { get; set; }
        public string OKATO { get; set; }
        public Nullable<decimal> COUNTRY_ID { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
    }
}
